replicaCount: 1
image:
  repository: redis
  tag: 7-alpine
  pullPolicy: IfNotPresent

fullnameOverride: "redis"

service:
  port: 6379
  targetPort: 6379

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"