apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
        - name: wait-for-zookeeper
          image: busybox
          command: [ "sh", "-c", "until nc -z zookeeper {{ .Values.zookeeper.port }}; do echo waiting for zookeeper; sleep 5; done" ]
      containers:
        - name: kafka
          image: {{ .Values.kafka.image }}
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.kafka.port }}
          envFrom:
            - configMapRef:
                name: kafka-configmap