apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.zookeeper.image }}
          resources:
            {{- toYaml .Values.zookeeper.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.zookeeper.port }}
          envFrom:
            - configMapRef:
                name: zookeeper-configmap