apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-chart.fullname" . }}
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}