replicaCount: 1
image:
  repository: asia-northeast3-docker.pkg.dev/engaged-proxy-460415-d1/highfive-registry/ai-engine-service
  tag: "latest"
  pullPolicy: IfNotPresent

fullnameOverride: "ai-engine-service"

service:
  port: 8084

dependency:
  api_gateway:
    service_name: "api-gateway"
    port: 8080

resources:
  requests:
    cpu: "300m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 100
  periodSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 100
  periodSeconds: 5
  failureThreshold: 3