apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-collector-chart.fullname" . }}
  labels:
    {{- include "data-collector-chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "data-collector-chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
