apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "board-service-chart.fullname" . }}
  labels:
    {{- include "board-service-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "board-service-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "board-service-chart.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-api-gateway
          image: busybox:1.36
          command: [ 'sh', '-c', 'until wget --spider http://{{ .Values.dependency.api_gateway.service_name }}:{{ .Values.dependency.api_gateway.port}}/actuator/health; do echo waiting for api-gateway; sleep 5; done' ]
        - name: wait-for-user-service
          image: busybox:1.36
          command: [ 'sh', '-c', 'until wget --spider http://{{ .Values.dependency.user_service.service_name }}:{{ .Values.dependency.user_service.port}}/actuator/health; do echo waiting for user-service; sleep 5; done' ]
        - name: wait-for-mongodb
          image: busybox
          command: [ 'sh', '-c', 'until nc -z {{ .Values.dependency.mongodb.service_name }} {{ .Values.dependency.mongodb.port }}; do echo waiting for mongodb; sleep 5; done' ]
        - name: wait-for-redis
          image: busybox
          command: [ 'sh', '-c', 'until nc -z {{ .Values.dependency.redis.service_name }} {{ .Values.dependency.redis.port }}; do echo waiting for redis; sleep 5; done' ]
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: board-service-secret
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always