apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-gateway-chart.fullname" . }}
  labels:
    {{- include "api-gateway-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api-gateway-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api-gateway-chart.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-discovery
          image: busybox:1.36
          command: ['sh', '-c', 'until wget --spider http://{{ .Values.dependency.discovery.service_name }}:{{ .Values.dependency.discovery.port }}/actuator/health; do echo waiting for discovery; sleep 5; done']
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: api-gateway-secret
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always