apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "discovery-chart.fullname" . }}
  labels:
    {{- include "discovery-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "discovery-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: discovery
      labels:
        {{- include "discovery-chart.labels" . | nindent 8 }}
    spec:
      containers:
        - name: discovery
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
      restartPolicy: Always