apiVersion: v1
kind: Service
metadata:
  name: {{ include "discovery-service-chart.fullname" . }}
  labels:
    {{- include "discovery-service-chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "discovery-service-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
      name: http
