replicaCount: 1
image:
  repository: asia-northeast3-docker.pkg.dev/engaged-proxy-460415-d1/highfive-registry/api-gateway
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 8080

resources:
  requests:
    cpu: "300m"
    memory: "512Mi"
  limits:
    cpu: "700m"
    memory: "1Gi"

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 100
  periodSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 100
  periodSeconds: 5
  failureThreshold: 3

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
          port: 8080