---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgBAaLKzXu+L3IwIoTq4kQQHkOcmY6PV/LDiIV1O4l1tjcgk738sURu+2bEyMUQOAP9u27aPHv5VXMIdJqmHNs2SRRdlge1QmJY72oIDuLGbhZKibm2/vjg+4A/Ygvq0B+pFg9Ei/JWOEuqEFcWPmawSymSEQEe0WTBkiI6cKpagHwYzuc7t/l0coK34AHUmEWR4R5ElLUibUFtcK/oGLrvHfxOvzyv4hDWL0EiC5dj+zXIOQLLL+tbYu1BQJZA8zRzMISL82l2FG+56DsWjvdd/332g0bL16gdGeoLRaVfcKOUHmR3SOaAQipj+QrR3LmmztS0JqPl48NW9Vy92snQuiq9VyvaoJP9+i1HMBn1qsoEvaMb4cLvtEMsBN4xvDMZ/kv2BzJ1frWogaKFkH2UWZcY+ubz6T9tMWIII2CZ871zkOS3/gMJ5vu3Ohq0qJjEh6HQITm1K56hPBLGPCqr9hyNjzJzwzetf4GZ2FYK9yJLroMZGYHp+MPyIJJplCVMbx0gExE9Jc1oT471SKPx8qsjgYquno5LYN1DF8PLAdtW+F+8xTUWH9nvx1Dfkve6zSZpEUU+ABdlHjUrdRjbd93D26dnL0KZnGdjKBKyqm9LVpvJ+7RO9kbXtVHNZJkS7Pu8V8ThIFH7N2mktS3V3VmztYgqdixdzuEBYoRc79gFNrWwhXci4ZqNTwMs1109RxaVU/RS1w11jD23CaA==
    MONGO_INITDB_ROOT_USERNAME: AgB4XMz2pjCj4ZTgZ6vAK1FxmLR4P7+Ex6MIamtVn8qVgsKvC3nPoapaFSPVWIIdo5v1MD7ezdpWoe0zEBVVgf3xTseKCJQy771f1GM92A1elAldpSTBWjLpTWELNs1EfUz9FFaJ4dZsj/6Pj5FS1ZnZqwGbTbq+PYjzrfXUk0ERwl1TSxTShhISWi8JHip2EMSsgoYA1573+oeC11+RTINbtXISrF/1WBOF01+vWWvtbpjUnCh4psug8cFBZR0KnQELI2QX9qgnltzHVMkReaNyvcN6MdqNKEwn1do89s9P9BHGFi6aymZmdodqZZrNk3E5qj32MsQqfOtAMKqxTtKAabhlAOeORaTR4tkVsmOUWsUpwVOpmN0mtfAhU88Jfxerzo1rvInWng/kQ36AQ+Pojk3ilaoZqBjHNO+LyAKKbypHCR+ynjyrP3UOXmx7e4XYJO/4w5qLizX/A0222Bkf4e0Wfmm/lxo2WK8O0+bwglbBhawEKwYTSwDuZlu1TtLvXwOkKnrtGiy02AyozvfVYLW9FwJILjUyY2WlE7DNOvI+JNzDENB90gbpJ4pWJLRbJtdEo5GiAFquRmgGvQX4rjutM3UYCLhzFD9AJ8TVvPl5yLMoVD0TqfKu+3Mggj1TbBvp2fCmoGuQPNVP8cnc/Rz0Rs1wyBx7e1cIChsU9zblx4UvAvP2391quR5CpTl1fdt18wykOzSZgqeJFm8Huw==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default
    type: opaque
