apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo-chart.fullname" . }}
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}