apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-engine-service-chart.fullname" . }}
  labels:
    {{- include "ai-engine-service-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ai-engine-service-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ai-engine-service-chart.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-api-gateway
          image: busybox:1.36
          command: [ "sh", "-c", "until wget --spider http://{{ .Values.dependency.api_gateway.service_name }}:{{ .Values.dependency.api_gateway.port }}/actuator/health; do echo waiting for api-gateway; sleep 5; done" ]
      containers:
        - name: ai-engine-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: ai-engine-service-secret
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always