apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-engine-service-chart.fullname" . }}
spec:
  selector:
    {{- include "ai-engine-service-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
      targetPort: http